// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzjinyvklrkymiebjgsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6amlueXZrbHJreW1pZWJqZ3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzA4MzcsImV4cCI6MjA3MTAwNjgzN30.4MG_4th2xj5h9PLq2RIWmlAMxisix4WRAqig4iRsL64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});